language: python
sudo: false
python: 2.7
env:
  matrix:
    - TOXENV=py26-django12
    - TOXENV=py27-django12
    - TOXENV=py26-django13
    - TOXENV=py27-django13
    - TOXENV=py26-django14
    - TOXENV=py27-django14
    - TOXENV=py26-django15
    - TOXENV=py27-django15
    - TOXENV=py32-django15
    - TOXENV=py33-django15
    - TOXENV=py34-django15
    - TOXENV=py26-django16
    - TOXENV=py27-django16
    - TOXENV=py32-django16
    - TOXENV=py33-django16
    - TOXENV=py34-django16
    - TOXENV=py27-django17
    - TOXENV=py32-django17
    - TOXENV=py33-django17
    - TOXENV=py34-django17

install:
  - pip install tox
script: tox
